[build]
  # No build command needed for static HTML/CSS/JS site
  publish = "."
  
[build.environment]
  # Set Node.js version if needed for any build processes
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules for clean URLs
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/member-login"
  to = "/member-profile.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/become-a-member.html"
  status = 200

# Handle 404s by serving the main page (for SPA-like behavior)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404